export default [
  {
    id: 1,
    titulo: "Funda para Guitarras",
    img: "../src/images/funda-para-guitarras.png",
    descripcion: "Funda acolchonada que sirve para guitarras clásicas y folk.",
    categoria: "Accesorios",
    precio: "550",
  },
  {
    id: 2,
    titulo: "Funda para Teclado",
    img: "../src/images/funda-para-teclado.png",
    descripcion:
      "Funda acolchonada e impermeable para teclado de tamaño 5 octavas.",
    categoria: "Accesorios",
    precio: "550",
  },
  {
    id: 3,
    titulo: "Guitarra Clásica",
    img: "../src/images/guitarra-clasica.png",
    descripcion:
      "Sus características de construcción y la calidad de su sonido, además de su atractivo acabado, sitúan estas guitarras por encima de sus competidoras en cuanto a prestaciones.",
    categoria: "Cuerda",
    precio: "1550",
  },
  {
    id: 4,
    titulo: "Ukelele Seaside Soprano Natural",
    img: "../src/images/ukelele.png",
    descripcion:
      "El Ukulele Seaside es la mejor solución con un sonido inspirador, compacto, cómodo y fácil de transportar, este uke soprano es ideal para principiantes o cualquiera que quiera añadir su sonido alegre a su música.",
    categoria: "Cuerda",
    precio: "1550",
  },
  {
    id: 5,
    titulo: "Bajo Eléctrico Player Precision",
    img: "../src/images/bajo-electrico.png",
    descripcion:
      "Con su estilo de tocar suave y su porte, este bajo estruendoso está listo para entrar al escenario.",
    categoria: "Cuerda",
    precio: "1550",
  },
  {
    id: 6,
    titulo: "Bateria de 5 Cuerpos",
    img: "../src/images/bateria-de-5-cuerpos.png",
    descripcion:
      "Presentamos Spectrum: construido a partir de capas combinadas de banda ancha, corte de arce y álamo seco y liviano hecho con un acabado mate irresistible.",
    categoria: "Percusión",
    precio: "990",
  },
  {
    id: 7,
    titulo: "Módulo Octapad",
    img: "../src/images/octapad.png",
    descripcion: "El diseño original de Octapad que hizo historia y marcó el camino futuro en lo que se refiere a módulos de percusión incluyendo sonidos modernos de batería y percusión.",
    categoria: "Percusión",
    precio: "1250",
  },
  {
    id: 8,
    titulo: "Cajón Acústico",
    img: "../src/images/cajon-acustico.png",
    descripcion: "Cajón de origen brasileño con bordona de 12 hilos.",
    categoria: "Percusión",
    precio: "990",
  },
  {
    id: 9,
    titulo: "Set de percusión",
    img: "../src/images/set-de-percusion.png",
    descripcion: "Triángulos, platillos, cowbell, pandereta, etc",
    categoria: "Percusión",
    precio: "1500",
  },
  {
    id: 10,
    titulo: "Trombón",
    img: "../src/images/trombon.png",
    descripcion: "Los modelos estándar son trombones duraderos de alta calidad que ofrecen una entrada perfecta en el mundo de la música.",
    categoria: "Viento",
    precio: "2500",
  },
  {
    id: 11,
    titulo: "Saxo Alto",
    img: "../src/images/saxo-alto.png",
    descripcion: "Ofrecen un sonido de saxofón característicamente brillante con una entonación excelente y algunas características de calidad sorprendentemente alta .",
    categoria: "Viento",
    precio: "2900",
  },
  {
    id: 12,
    titulo: "Armónica",
    img: "../src/images/armonica.png",
    descripcion: "Con una construcción sólida, una forma tradicional y tono articulado, esta armónica diatónica de 10 agujeros ofrece el clásico sonido fiable.",
    categoria: "Viento",
    precio: "250",
  },
  {
    id: 13,
    titulo: "Flauta Contralto",
    img: "../src/images/flauta.png",
    descripcion: "Las flautas dulces de resina ABS son duraderas y fáciles de mantener a la vez que brindan un sonido similar al de la madera natural.",
    categoria: "Viento",
    precio: "450",
  },
  {
    id: 14,
    titulo: "Atril Partituras",
    img: "../src/images/atril-partituras.png",
    descripcion: "Atril para partituras de altura ajustable. Cuenta con una solida base, acabado negro, plegable y de fácil transporte.",
    categoria: "Accesorios",
    precio: "450",
  },
  {
    id: 15,
    titulo: "Jirafa Micrófono",
    img: "../src/images/jirafa-microfono.png",
    descripcion: "Base de tripode plástica. Patas antideslizantes. Largo total de 1,5 mts. Fácil de transportar.",
    categoria: "Accesorios",
    precio: "750",
  },
  {
    id: 16,
    titulo: "Micrófono Inalámbrico",
    img: "../src/images/microfono-inalambrico.png",
    descripcion: "Incluye 1 micrófono de mano,receptor , adaptador de corriente. Cable plug-plug ,pilas",
    categoria: "Accesorios",
    precio: "850",
  },
  {
    id: 17,
    titulo: "Caja Activa con Batería",
    img: "../src/images/caja-activa.png",
    descripcion: "Con control Remoto incluido - Potencia: 45W RMS (1% THD+N) 100W PEAK (10 THD+N) - Bateria 4.5A 12v - Medidas 482x395x750mm.",
    categoria: "Accesorios",
    precio: "3500",
  },
  {
    id: 18,
    titulo: "Consola Digital",
    img: "../src/images/consola-digital.png",
    descripcion: "Mesa de mezclas digital con 48 canales de entrada, 16 buses estéreo, 4 salidas principales, 8 buses de matriz, una interfaz de usuario con 24 faders motorizados de 100 mm y una pantalla táctil de 10.",
    categoria: "Accesorios",
    precio: "9900",
  },
  {
    id: 19,
    titulo: "Monitor De Piso Activo",
    img: "../src/images/monitor-de-piso.png",
    descripcion: "Monitor activo con diseño coaxial bidireccional.",
    categoria: "Accesorios",
    precio: "9900",
  },
  {
    id: 20,
    titulo: "Pack Interfaz De Audio",
    img: "../src/images/pack-audio.png",
    descripcion: "Completo kit Hardware/Software de grabación. Incluye micrófono y auriculares.",
    categoria: "Accesorios",
    precio: "9900",
  },
];
